Repository community-outpost/GenHub, pull requests merged in 2025-06, with the labels that each got.

#33 Add code guidelines to the repository
  coding-style.md
Labels: Documentation

#40 Added ci.yml workflow for builds and tests
  .github/workflows/ci.yml
Labels: Enhancement

#38 Adding Testing Infrastructure
  .gitignore
  GenHub/Directory.Packages.props
  GenHub/GenHub.Core/GenHub.Core.csproj
  GenHub/GenHub.Linux/GenHub.Linux.csproj
  GenHub/GenHub.Tests/GenHub.Tests.Core/GenHub.Tests.Core.csproj
  GenHub/GenHub.Tests/GenHub.Tests.Linux/GenHub.Tests.Linux.csproj
  GenHub/GenHub.Tests/GenHub.Tests.Windows/GenHub.Tests.Windows.csproj
  GenHub/GenHub.Windows/GenHub.Windows.csproj
  GenHub/GenHub.sln
  GenHub/GenHub/GenHub.csproj
  stylecop.json
Labels: Testing
