Repository community-outpost/GenHub, pull requests merged in 2025-07, with the labels that each got.

#59 Refactor(ci): Fix windows tests not failing ci checks
  .github/workflows/ci.yml
Labels: Bug, Major, Testing, Refactor

#57 Fixes remaining documentation warnings thrown by Stylecop
  GenHub/GenHub.Core/GenHub.Core.csproj
  GenHub/GenHub.Core/Models/GameVersions/GameType.cs
  GenHub/GenHub.Linux/GenHub.Linux.csproj
  GenHub/GenHub.Tests/GenHub.Tests.Core/GenHub.Tests.Core.csproj
  GenHub/GenHub.Tests/GenHub.Tests.Core/GlobalSuppressions.cs
  GenHub/GenHub.Tests/GenHub.Tests.Linux/GenHub.Tests.Linux.csproj
  GenHub/GenHub.Tests/GenHub.Tests.Windows/GenHub.Tests.Windows.csproj
  GenHub/GenHub.Windows/GenHub.Windows.csproj
  GenHub/GenHub/App.axaml.cs
  GenHub/GenHub/AppLocator.cs
  GenHub/GenHub/GenHub.csproj
  GenHub/GenHub/Infrastructure/DependencyInjection/GameDetectionModule.cs
Labels: Documentation

#58 Move native win32 commands to a NativeMethods class to make stylecop happy
  GenHub/GenHub.Windows/NativeMethods.cs
  GenHub/GenHub.Windows/Program.cs
Labels: Refactor

#46 Extends #45: Refactor platform specific game detectors
  GenHub/GenHub.Core/DummyGameDetector.cs
  GenHub/GenHub.Core/Extensions/GameInstallations/InstallationExtensions.cs
  GenHub/GenHub.Core/GenHub.Core.csproj
  GenHub/GenHub.Core/IGameDetector.cs
  GenHub/GenHub.Core/Interfaces/GameInstallations/IGameInstallation.cs
  GenHub/GenHub.Core/Models/Enums/GameInstallationType.cs
  GenHub/GenHub.Core/Models/Enums/GameType.cs
  GenHub/GenHub.Core/Models/GameInstallations/GameInstallation.cs
  GenHub/GenHub.Core/Models/GameVersions/GameVersion.cs
  GenHub/GenHub.Linux/GameInstallations/LinuxInstallationDetector.cs
  GenHub/GenHub.Linux/GameInstallations/SteamInstallation.cs
  GenHub/GenHub.Linux/GameInstallations/WineInstallation.cs
  GenHub/GenHub.Linux/LinuxGameDetector.cs
  GenHub/GenHub.Linux/Program.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/GameInstallations/GameInstallationDetectionOrchestratorTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/GameVersions/GameVersionDetectionOrchestratorTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Infrastructure/DependencyInjection/SharedViewModelModuleTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Models/GameInstallations/GameInstallationTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Models/GameVersions/GameVersionTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Services/GameDetectionServiceTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/ViewModels/MainViewModelTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Linux/Gameinstallations/LinuxInstallationDetectorTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Linux/Gameinstallations/SteamInstallationTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Linux/Gameinstallations/WineInstallationTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Windows/Gameinstallations/WindowsInstallationDetectorTests.cs
  GenHub/GenHub.Windows/GameInstallations/EaAppInstallation.cs
  GenHub/GenHub.Windows/GameInstallations/SteamInstallation.cs
  GenHub/GenHub.Windows/GameInstallations/WindowsInstallationDetector.cs
  GenHub/GenHub.Windows/Installations/EaAppInstallation.cs
  GenHub/GenHub.Windows/Installations/SteamInstallation.cs
  GenHub/GenHub.Windows/Program.cs
  GenHub/GenHub.Windows/WindowsGameDetector.cs
  GenHub/GenHub/App.axaml.cs
  GenHub/GenHub/Common/ViewModels/MainViewModel.cs
  GenHub/GenHub/Features/GameInstallations/GameInstallationDetectionOrchestrator.cs
  GenHub/GenHub/Features/GameVersions/GameVersionDetectionOrchestrator.cs
  GenHub/GenHub/Infrastructure/DependencyInjection/AppServices.cs
  GenHub/GenHub/Infrastructure/DependencyInjection/GameDetectionModule.cs
  GenHub/GenHub/Infrastructure/DependencyInjection/SharedViewModelModule.cs
  GenHub/GenHub/Services/GameDetectionService.cs
Labels: Enhancement, Refactor

#78 feat(workspace): Implement workspace management system
  GenHub/GenHub.Core/Interfaces/Launching/IGameLauncher.cs
  GenHub/GenHub.Core/Interfaces/Manifest/IContentManifestBuilder.cs
  GenHub/GenHub.Core/Interfaces/Workspace/IFileOperationsService.cs
  GenHub/GenHub.Core/Interfaces/Workspace/IWorkspaceManager.cs
  GenHub/GenHub.Core/Interfaces/Workspace/IWorkspaceStrategy.cs
  GenHub/GenHub.Core/Interfaces/Workspace/IWorkspaceValidator.cs
  GenHub/GenHub.Core/Models/Enums/WorkspaceStrategy.cs
  GenHub/GenHub.Core/Models/Launching/GameLaunchConfiguration.cs
  GenHub/GenHub.Core/Models/Launching/GameProcessInfo.cs
  GenHub/GenHub.Core/Models/Manifest/InstallationInstructions.cs
  GenHub/GenHub.Core/Models/Results/LaunchResult.cs
  GenHub/GenHub.Core/Models/Validation/ValidationIssueType.cs
  GenHub/GenHub.Core/Models/Workspace/WorkspaceConfiguration.cs
  GenHub/GenHub.Core/Models/Workspace/WorkspaceInfo.cs
  GenHub/GenHub.Core/Models/Workspace/WorkspacePreparationProgress.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/FileOperationsServiceTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/HybridCopySymlinkStrategyTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/StrategyTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/WorkspaceIntegrationTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/WorkspaceManagerTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/WorkspaceStrategyBaseTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Core/Features/Workspace/WorkspaceValidatorTests.cs
  GenHub/GenHub.Tests/GenHub.Tests.Windows/Features/Workspace/WindowsFileOperationsServiceTests.cs
  GenHub/GenHub.Windows/Features/Workspace/WindowsFileOperationsService.cs
  GenHub/GenHub.Windows/Program.cs
  GenHub/GenHub/Features/Launching/GameLauncher.cs
  GenHub/GenHub/Features/Manifest/ContentManifestBuilder.cs
  GenHub/GenHub/Features/Workspace/FileOperationsService.cs
  GenHub/GenHub/Features/Workspace/Strategies/FullCopyStrategy.cs
  GenHub/GenHub/Features/Workspace/Strategies/HardLinkStrategy.cs
  GenHub/GenHub/Features/Workspace/Strategies/HybridCopySymlinkStrategy.cs
  GenHub/GenHub/Features/Workspace/Strategies/SymlinkOnlyStrategy.cs
  GenHub/GenHub/Features/Workspace/Strategies/WorkspaceStrategyBase.cs
  GenHub/GenHub/Features/Workspace/WorkspaceManager.cs
  GenHub/GenHub/Features/Workspace/WorkspaceValidator.cs
  GenHub/GenHub/Infrastructure/DependencyInjection/AppServices.cs
  GenHub/GenHub/Infrastructure/DependencyInjection/WorkspaceModule.cs
Labels: Enhancement, Major, Architecture
